version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: docker
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - data_dot:/var/lib/postgresql/dot_dump
volumes:
  data_dot: